Repository wecode-bootcamp-korea/23-2nd-BeerBnB-frontend, pull requests merged in 2021-08, with the labels that each got.

#2 [23기 배윤아] Add : 상세페이지 레이아웃
  package-lock.json
  package.json
  public/index.html
  src/Routes.js
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailContent.js
  src/pages/Detail/DetailModal.js
  src/pages/Detail/DetailTitle.js
  src/pages/Detail/ImageSlider.js
  src/pages/Detail/Reservation.js
Labels: Status: 수정 요청

#1 [23기 이나현] Modify: 수정사항 반영
  public/locationList.json
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Footer/LinkLi.js
  src/components/Nav/Nav.js
  src/components/Nav/NavMainComponent/NavCheckInandOut.js
  src/components/Nav/NavMainComponent/NavLocation.js
  src/components/Nav/NavRight.js
  src/components/Nav/NavSearchBar.js
  src/components/Nav/SearchBottom.js
  src/styles/GlobalStyle.js
  src/styles/mixin.js
Labels: Status: 리뷰 요청

#3 [23기 김가영] MODIFY: merge, conflict 해결
  package-lock.json
  package.json
  public/images/Close.png
  public/images/kakao_login.png
  public/images/kakao_logout.png
  public/index.html
  public/manifest.json
  src/Routes.js
  src/config.js
  src/index.js
  src/pages/Login/KakaoLogin/KakaoLogin.js
  src/pages/Login/Login.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#5 [23기 배윤아] Add : 상세페이지 기능 구현 및 달력 컴포넌트 수정
  package-lock.json
  package.json
  public/data/DetailData.json
  src/config.js
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailContent.js
  src/pages/Detail/DetailModal.js
  src/pages/Detail/DetailTitle.js
  src/pages/Detail/ImageSlider.js
  src/pages/Detail/Reservation.js
Labels: Status: Accepted

#7 [23기 이나현] [MODIFY] Nav Function 수정
  package-lock.json
  package.json
  public/locationList.json
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Nav/Nav.js
  src/components/Nav/NavMainComponent/NavCheckInandOut.js
  src/components/Nav/NavMainComponent/NavLocation.js
  src/components/Nav/NavSearchBar.js
  src/components/Nav/SearchBottom.js
Labels: Status: Accepted

#6 [23기 이나현]FIXED: conflict 해결
  package-lock.json
  package.json
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Nav/KakaoLogin.js
  src/components/Nav/NavRight.js
  src/pages/Login/Login.js
  src/pages/Main/Main.js
  src/pages/Main/beerImg.jpg
Labels: Status: 리뷰 요청

#4 [23기 황문실] MODIFY: 리스트 페이지 레이아웃
  package-lock.json
  package.json
  public/data/List/mapMockData.json
  public/images/heart.png
  public/images/left.png
  public/images/listImage.jpeg
  public/images/listImage2.jpeg
  public/images/listImage3.jpeg
  public/images/right.png
  public/index.html
  public/locationList.json
  src/Routes.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/List/Aside/ImgLists.js
  src/pages/List/Aside/ImgSlider.js
  src/pages/List/Aside/Map.js
  src/pages/List/Aside/Paging.js
  src/pages/List/List.js
  src/styles/GlobalStyle.js
  yarn.lock
Labels: Status: Accepted
